### ISSUE TITLE
WP Chatbot ERROR: Invalid URL

### ISSUE THREAD

**Issue by lucianosilvi** [krilor/wp-chatbot#47]
Hi, I've setup the plugin, having the request url like http://localhost:8000/query/, I've set the JSONPath properly and the "Integration type" to "Generic request settings".

However when I try to use the chatbot, after sending an input I don't get an answer, and exploring the console in Chrome I see the message "WP Chatbot Error: Invalid URL".

Is this a bug or some wrong specified setting?

Thanks

**Comment by krilor** [comment]
Hi Luciano

I think it might be caused by the plugin using wp_safe_remote_*() in stead of the "usual" wp_remote_*().
[wp_http_validate_url](https://developer.wordpress.org/reference/functions/wp_http_validate_url/) ends up flagging the URL as invalid for some reason.

I'm thinking that it might not make sense to use wp_safe_remote_*(), since the urls should have been checked and OK'ed by admin before setting it up.

I've created a [branch where removed the _safe functions](https://github.com/krilor/wp-chatbot/tree/allow-unsafe-urls). Could you maybe try that and let me know how it goes?

If it doesn't work, please share your settings so I can have a look.

**Comment by lucianosilvi** [comment]
Great! It's working now. I think maybe it was due to the port number, reading the wp_http_validate_url function it allows only certain ports, but in these cases, when working locally we need more flexibility.

Thanks!
